# ---------------------------------------------
# Overleaf Community Edition (overleaf/overleaf)
# ---------------------------------------------
# Create a full Latex installation image

FROM sharelatex/sharelatex:latest

RUN tlmgr install scheme-full
